### PR TITLE
Font awesome icons

### PR DESCRIPTION
**Pull request by asubedy**
Replaced **Utf8** with **Font Awesome 5** icons. Below are the screenshot of the same.

image
image

**Installed packages:** 
1. ````sveltejs-fontawesome````
2. ````@fortawesome/free-solid-svg-icons````
3. ````@fortawesome/free-brands-svg-icons````

### CODE REVIEW

**Comment by mannprerak2** [comment]
The icons look fine, but I think the color should be grey (Try to match the color with the text along with it)

Also, is `@fortawesome/free-brands-svg-icons` required?

**Comment by asubedy** [comment]
Ok I will change the color.

> Also, is @fortawesome/free-brands-svg-icons required?

No it is not required that's the wrong package sorry the correct packages installed are:
    ````sveltejs-fontawesome````
    ````@fortawesome/free-solid-svg-icons````
   ````@fortawesome/free-regular-svg-icons````

The regular one is for the save icon. The solid version of it was not looking nice.

**Comment by asubedy** [comment]
These are the changed icons color (I decreased the opacity of the icons):
image
image

**Comment by mannprerak2** [comment]
Looks fine, can you send me SS of the new tab screen in dark mode?
Click on the sun icon to switch to dark mode, and if it doesn't match, you'll have to update the icons of dark theme

**Comment by asubedy** [comment]
image
Here you go.

**Comment by mannprerak2** [comment]
Thanks, please fix the icons for dark theme.

**Comment by asubedy** [comment]
How should I change them can you give some advice? Thank you

**Comment by mannprerak2** [comment]
There are 2 css files which are placed according to theme, 
global-light.css and global-dark.css

you can create a CSS variable in both of them and set the colors of icon, and then use it like this
```html
        border-bottom: 1px solid var(--collection-separator);
```

**Comment by asubedy** [comment]
Now the icons changes the color according to the theme. Here are the screenshot.

**LIGHT THEME -**
image

**DARK THEME -**
image

**Review by mannprerak2 — APPROVED** [review]

**Comment by mannprerak2** [comment]
@asubedy 
Can you also change the ☀and ☽ icons used to change the theme, reduce the size of Delete and Search a little (in the NewTabs page)?

You can create a New PR for this.

**Comment by asubedy** [comment]
All right on it,

**Comment by asubedy** [comment]
Hello can you help me i think i broke something i had changed the icon size and changed the toggle button but when I tried to create a pull request but it gave me an error saying cannot merge this PR. I figured i need to merge this pr in my master but still after doing that it gave me same error. Sorry to trouble you but please help me out.

**Comment by asubedy** [comment]
Should I delete the forked repo and fork this repo again and do the require changes or is there some way to fix this without doing that.

**Comment by mannprerak2** [comment]
What you should do is 
Create a new branch on master and make the channges.
```
git checkout master
git pull upstream master
git branch new-branch
git checkout new-branch
```
Now you can do the changes and make a new PR.

Note: You have to set upstream manually, see https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/configuring-a-remote-for-a-fork

**Comment by asubedy** [comment]
Thank you so much, I thought I really messed everything up. I have created the new PR.

**Pull request merged**
